---
all:
  hosts:
    vm0:
      ansible_host: 192.168.173.8
      ansible_connection: local
    vm3:
      ansible_host: 192.168.173.3
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa
    vm2: 
      ansible_host: 192.168.173.7
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa
      #ansible_python_interpreter: /usr/bin/python3
  children:
    slaves:
      hosts:
        vm2:
        vm3:
    masters:
      hosts:
        vm0:
    ubuntu:
      hosts:
        vm2:
        vm3:
