---
- hosts: vm2
  become: yes
  gather_facts: false
  
  pre_tasks:
    
    #note this installation of python2 only works on Ubuntu VMs
    - name: Install python2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when:
        - output.stdout !=""
        - output.stdout !="\r\n"
      when: inventory_hostname in groups['ubuntu']
    
    - name: Gathering Facts
      setup:
  
    - name: "Load role variables"
      include_vars: "./vars/{{ item }}.yml"
      with_items:
        - "append-hostname"
        - "apache"
        - "openssl"
    
    - name: "Load OS specific variables for mysql role"
      include_vars: "{{ item }}"
      with_first_found:
        - files:
          - "./vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}_mysql.yml"
          - "./vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}_mysql.yml"
          - "./vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}_mysql.yml"
          - "./vars/{{ ansible_distribution }}_mysql.yml"
          - "./vars/{{ ansible_os_family }}_mysql.yml"
          - "./vars/mysql.yml"
    
    - name: "Load role variables for wordpress play"
      include_vars: "./vars/wordpress/{{ item }}.yml"
      with_items:
        - "mysql"
    
    - name: "Get mysql password from password-file"
      include_role: 
        name: password-file
      vars:
        path: /root
        pass_id: mysql_root
        pass_len: 32
    
    - set_fact:
        mysql_root_password: "{{ passwords.mysql_root }}"
    
    - name: "Get mysql wordpress password from password-file"
      include_role: 
        name: password-file
      vars:
        path: /root
        pass_id: mysql_wordpress
        pass_len: 32
    
    #add mysql password to mysql_users[0] dictionary
    - set_fact:
        tmp: '{"password":"{{ passwords.mysql_wordpress }}" }'
    - set_fact:
        mysql_users: "[ {{ mysql_users[0]|combine( tmp ) }} ]"
      
    - name: "Load OS specific variables for php role as needed for wordpress play"
      include_vars: "{{ item }}"
      with_first_found:
        - files:
          - "./vars/wordpress/{{ ansible_distribution }}-{{ ansible_distribution_version }}_php.yml"
          - "./vars/wordpress/{{ ansible_distribution }}-{{ ansible_distribution_release }}_php.yml"
          - "./vars/wordpress/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}_php.yml"
          - "./vars/wordpress/{{ ansible_distribution }}_php.yml"
          - "./vars/wordpress/{{ ansible_os_family }}_php.yml"
  roles:
    - append-hostname
    - geerlingguy.apache
    - weareinteractive.openssl
    - geerlingguy.php
    - geerlingguy.mysql
    - geerlingguy.php-mysql
    - geerlingguy.apache-php-fpm
#    - wordpress
    
#Ubuntu packages from heat/cloud-init
#- apache2 (DONE -> apache)
#- mysql-server (DONE -> mysql-server)
#- php (DONE -> php)
#- php-dev (DONE -> php)
#- libapache2-mod-php (DONE -> php)
#- php-mcrypt (DONE -> php)
#- php-mysql (DONE -> php)
#- php-curl (DONE -> php)
#- php-gd (DONE -> php)
#- php-mbstring (DONE -> php)
#- php-xml (DONE -> php)
#- php-xmlrpc (DONE -> php)
#- php-fpm (DONE -> php)
#- libssh2-1-dev
#- fail2ban
#- software-properties-common